"""Application configuration."""

from django.apps import AppConfig


class FuelRouteConfig(AppConfig):
    name = "fuelroute"
    verbose_name = "Fuel route optimizer"

    def ready(self) -> None:
        """Warm the station table so the first request does not pay for parsing."""
        import contextlib

        from fuelroute import stations

        # The dataset is generated by scripts/build_dataset.py. Starting without it is
        # allowed so that the build step can run inside a container that has not yet
        # produced the file.
        with contextlib.suppress(FileNotFoundError):
            stations.load_stations()
